### ISSUE TITLE
[BUG] Build fails

### ISSUE THREAD

**Issue by geoidesic** [typhonjs-fvtt-demo/essential-svelte-esm#11]
**Module Version:** v0.0.14

**Describe the bug**
App doesn't build using `npm build`

**To Reproduce**
1. Copy the `essential-svelte-esm` folder into `modules` folder
2. Run `yarn`
3. Run `yarn build`

**Expected behavior**
Should build

**Error**
```

yarn build
yarn run v1.22.19
$ vite build
vite v3.2.5 building for production...
transforming (112) view/position/app-control/dialog/draggable/PosDraggable.svelte
/ui/denim075.png referenced in /Users/noeldacosta/Library/Application Support/FoundryVTT/Data/modules/essential-svelte-esm/node_modules/@typhonjs-fvtt/runtime/_dist/svelte/component/core/application/TJSApplicationShell.svelte?svelte&type=style&lang.css didn't resolve at build time, it will remain unchanged to be resolved at runtime
✓ 220 modules transformed.
12:17:23 PM [vite-plugin-svelte] dom compile done.
package                 files    time      avg
essential-svelte-esm       65   0.69s   10.7ms
'TJSSessionStorage' is not exported by node_modules/@typhonjs-fvtt/runtime/_dist/svelte/store/index.js, imported by src/view/app-state/session-storage/AppStateSessionApp.js
file: /Users/noeldacosta/Library/Application Support/FoundryVTT/Data/modules/essential-svelte-esm/src/view/app-state/session-storage/AppStateSessionApp.js:2:9
1: import { SvelteApplication }  from '@typhonjs-fvtt/runtime/svelte/application';
2: import { TJSSessionStorage }  from '@typhonjs-fvtt/runtime/svelte/store';
            ^
3:
4: import SessionAppShell        from './SessionAppShell.svelte';
error during build:
Error: 'TJSSessionStorage' is not exported by node_modules/@typhonjs-fvtt/runtime/_dist/svelte/store/index.js, imported by src/view/app-state/session-storage/AppStateSessionApp.js
    at error (file:///Users/noeldacosta/Library/Application%20Support/FoundryVTT/Data/modules/essential-svelte-esm/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///Users/noeldacosta/Library/Application%20Support/FoundryVTT/Data/modules/essential-svelte-esm/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
    at Module.traceVariable (file:///Users/noeldacosta/Library/Application%20Support/FoundryVTT/Data/modules/essential-svelte-esm/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
    at ModuleScope.findVariable (file:///Users/noeldacosta/Library/Application%20Support/FoundryVTT/Data/modules/essential-svelte-esm/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
    at ChildScope.findVariable (file:///Users/noeldacosta/Library/Application%20Support/FoundryVTT/Data/modules/essential-svelte-esm/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ClassBodyScope.findVariable (file:///Users/noeldacosta/Library/Application%20Support/FoundryVTT/Data/modules/essential-svelte-esm/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ChildScope.findVariable (file:///Users/noeldacosta/Library/Application%20Support/FoundryVTT/Data/modules/essential-svelte-esm/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at Identifier.bind (file:///Users/noeldacosta/Library/Application%20Support/FoundryVTT/Data/modules/essential-svelte-esm/node_modules/rollup/dist/es/shared/rollup.js:7439:40)
    at NewExpression.bind (file:///Users/noeldacosta/Library/Application%20Support/FoundryVTT/Data/modules/essential-svelte-esm/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
    at PropertyDefinition.bind (file:///Users/noeldacosta/Library/Application%20Support/FoundryVTT/Data/modules/essential-svelte-esm/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Screenshots**

**Browser:**
 - Foundry desktop

**Foundry Version:** 
Version 10 - Build 291

**Game System:** 
No system, this error happens before you get to that point.

**Comment by typhonrt** [comment]
Ah crap... Yeah.. This is one of the name changes in the forthcoming TRL update. Dang.. I forgot to make a branch of `essential-svelte-esm` in locally linked testing. It's probably been broken for a few days / less than a week. 

If you want to build things currently you can change that to `SessionStorage` instead of `TJSSessionStorage`. I gather that might be one of the only issues with things presently. 

You can also check out the latest release versus cloning the repo:
https://github.com/typhonjs-fvtt-demo/essential-svelte-esm/releases/tag/0.0.14

**Comment by typhonrt** [comment]
I reverted the accidental inclusion of new TRL class name changes.
